language: php

sudo: false

addons:
  apt_packages:
    - xvfb
    - firefox

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

before_script:
    - git clone https://github.com/fonsecas72/customfirefoxprofile.git tests/Resources/firefoxProfile/
    - composer install

script:
    - ./vendor/bin/phpunit

git:
  depth: 5